ecommerce:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: dev
      password: dev
      dbname: ecommerce
      port: 5432
      schema: public
      threads: 4